CREATE OR REPLACE TRIGGER TRG_01
AFTER INSERT
ON EMPLOYEE
BEGIN
    DBMS_OUTPUT.PUT_LINE('신입사원이 입사했습니다.');
END;
/
INSERT INTO EMPLOYEE VALUES (905, '길성춘', '690512-1151432',
'gil_sj@kh.or.kr', '01035464455', 'D5', 'J3',
'S5', 3000000, 0.1, 200, SYSDATE, NULL,
DEFAULT);

CREATE TABLE PRODUCT(
    PCODE NUMBER PRIMARY KEY,
    PNAME VARCHAR2(30),
    BRAND VARCHAR2(30),
    PRICE NUMBER,
    STOCK NUMBER DEFAULT 0
);

CREATE TABLE PRO_DETAIL(
    DCODE NUMBER PRIMARY KEY,
    PCODE NUMBER,
    PDATE DATE,
    AMOUNT NUMBER,
    STATUS VARCHAR2(10) CHECK (STATUS IN ('입고', '출고')),
    FOREIGN KEY (PCODE) REFERENCES PRODUCT(PCODE)
);

CREATE SEQUENCE SEQ_PCODE;
CREATE SEQUENCE SEQ_DCODE;

INSERT INTO PRODUCT
VALUES(SEQ_PCODE.NEXTVAL, '갤럭스노트8', '삼송', 900000, DEFAULT);
INSERT INTO PRODUCT
VALUES(SEQ_PCODE.NEXTVAL, '아이뽀8', '사과', 1000000, DEFAULT);
INSERT INTO PRODUCT
VALUES(SEQ_PCODE.NEXTVAL, '대륙폰', '샤우미', 600000, DEFAULT);

CREATE OR REPLACE TRIGGER TGR_02
AFTER INSERT ON PRO_DETAIL
    FOR EACH ROW
        BEGIN
            IF :NEW.STATUS = '입고'
            THEN
                UPDATE PRODUCT SET STOCK = STOCK + :NEW.AMOUNT
                WHERE PCODE = :NEW.PCODE;
            END IF;
            
            IF :NEW.STATUS = '출고'
            THEN
                UPDATE PRODUCT SET STOCK = STOCK - :NEW.AMOUNT
                WHERE PCODE = :NEW.PCODE;
            END IF;
END;
/

INSERT INTO PRO_DETAIL VALUES (SEQ_DCODE.NEXTVAL,1, SYSDATE, 5, '입고');
INSERT INTO PRO_DETAIL VALUES (SEQ_DCODE.NEXTVAL,2, SYSDATE, 10, '입고');
INSERT INTO PRO_DETAIL VALUES (SEQ_DCODE.NEXTVAL,3, SYSDATE, 20, '입고');
INSERT INTO PRO_DETAIL VALUES (SEQ_DCODE.NEXTVAL,1, SYSDATE, 1, '출고');
INSERT INTO PRO_DETAIL VALUES (SEQ_DCODE.NEXTVAL,2, SYSDATE, 7, '출고');
INSERT INTO PRO_DETAIL VALUES (SEQ_DCODE.NEXTVAL,3, SYSDATE, 11, '출고');

SELECT * FROM PRODUCT;
SELECT * FROM PRO_DETAIL;