            DROP TABLE "TB_GRADE";
        DROP TABLE "TB_STUDENT";
        DROP TABLE "TB_CLASS_PROFESSOR";
    DROP TABLE "TB_PROFESSOR";
    DROP TABLE "TB_CLASS";
DROP TABLE "TB_DEPARTMENT";


CREATE TABLE "TB_STUDENT" (
	"STUDENT_NO"	VARCHAR2(15)		NOT NULL,
	"STUDENT_NAME"	VARCHAR2(15)		NOT NULL,
	"STUDENT_SSN"	VARCHAR2(14)		NULL,
	"STUDENT_ADDRESS"	VARCHAR2(100)		NULL,
	"ENTRANCE_DATE"	DATE		NULL,
	"ABSENCE_YN"	CHAR(1)		NULL,
	"DEPARTMENT_NO"	VARCHAR2(10)		NOT NULL,
	"COACH_PROFESSOR_NO"	VARCHAR2(10)		NULL
);
COMMENT ON COLUMN "TB_STUDENT"."STUDENT_NO" IS '학번 YYYYNNNN으로 구성';
COMMENT ON COLUMN "TB_STUDENT"."STUDENT_NAME" IS '학생이름';

CREATE TABLE "TB_DEPARTMENT" (
	"DEPARTMENT_NO"	VARCHAR2(10)		NOT NULL,
	"DEPARTMENT_NAME"	VARCHAR2(30)		NOT NULL,
	"CATEGORY"	VARCHAR2(20)		NULL,
	"OPEN_YN"	CHAR(1)		NULL,
	"CAPACITY"	NUMBER		NULL
);



CREATE TABLE "TB_CLASS" (
	"CLASS_NO"	VARCHAR2(10)		NOT NULL,
	"PREATTENDING_CLASS_NO"	VARCHAR2(20)		NULL,
	"CLASS_NAME"	VARCHAR2(30)		NOT NULL,
	"CLASS_TYPE"	VARCHAR2(20)		NULL,
	"DEPARTMENT_NO"	VARCHAR2(10)		NOT NULL
);



CREATE TABLE "TB_CLASS_PROFESSOR" (
	"CLASS_NO"	VARCHAR2(10)		NOT NULL,
	"PROFESSOR_NO"	VARCHAR2(10)		NOT NULL
);



CREATE TABLE "TB_PROFESSOR" (
	"PROFESSOR_NO"	VARCHAR2(10)		NOT NULL,
	"PROFESSOR_NAME"	VARCHAR2(30)		NOT NULL,
	"PROFESSOR_SSN"	VARCHAR2(14)		NULL,
	"PROFESSOR_ADDRESS"	VARCHAR2(100)		NULL,
	"DEPARTMENT_NO"	VARCHAR2(10)		NOT NULL
);



CREATE TABLE "TB_GRADE" (
	"TERM_NO"	VARCHAR2(10)		NOT NULL,
	"STUDENT_NO"	VARCHAR2(15)		NOT NULL,
	"CLASS_NO"	VARCHAR2(10)		NOT NULL,
	"POINT"	NUMBER(3,2)		NULL
);

COMMENT ON COLUMN "TB_GRADE"."STUDENT_NO" IS '학번 YYYYNNNN으로 구성';

ALTER TABLE "TB_STUDENT" ADD CONSTRAINT "PK_TB_STUDENT" PRIMARY KEY (
	"STUDENT_NO"
);

ALTER TABLE "TB_DEPARTMENT" ADD CONSTRAINT "PK_TB_DEPARTMENT" PRIMARY KEY (
	"DEPARTMENT_NO"
);

ALTER TABLE "TB_CLASS" ADD CONSTRAINT "PK_TB_CLASS" PRIMARY KEY (
	"CLASS_NO"
);

ALTER TABLE "TB_CLASS_PROFESSOR" ADD CONSTRAINT "PK_TB_CLASS_PROFESSOR" PRIMARY KEY (
	"CLASS_NO",
	"PROFESSOR_NO"
);

ALTER TABLE "TB_PROFESSOR" ADD CONSTRAINT "PK_TB_PROFESSOR" PRIMARY KEY (
	"PROFESSOR_NO"
);

ALTER TABLE "TB_GRADE" ADD CONSTRAINT "PK_TB_GRADE" PRIMARY KEY (
	"TERM_NO",
	"STUDENT_NO",
	"CLASS_NO"
);
-----------------------------------
ALTER TABLE "TB_STUDENT" ADD CONSTRAINT "FK_TB_DEPARTMENT_TO_TB_STUDENT_1" FOREIGN KEY (
	"DEPARTMENT_NO"
)
REFERENCES "TB_DEPARTMENT" (
	"DEPARTMENT_NO"
);

ALTER TABLE "TB_STUDENT" ADD CONSTRAINT "FK_TB_PROFESSOR_TO_TB_STUDENT_1" FOREIGN KEY (
	"COACH_PROFESSOR_NO"
)
REFERENCES "TB_PROFESSOR" (
	"PROFESSOR_NO"
);

ALTER TABLE "TB_CLASS" ADD CONSTRAINT "FK_TB_DEPARTMENT_TO_TB_CLASS_1" FOREIGN KEY (
	"DEPARTMENT_NO"
)
REFERENCES "TB_DEPARTMENT" (
	"DEPARTMENT_NO"
);

ALTER TABLE "TB_CLASS_PROFESSOR" ADD CONSTRAINT "FK_TB_CLASS_TO_TB_CLASS_PROFESSOR_1" FOREIGN KEY (
	"CLASS_NO"
)
REFERENCES "TB_CLASS" (
	"CLASS_NO"
);

ALTER TABLE "TB_CLASS_PROFESSOR" ADD CONSTRAINT "FK_TB_PROFESSOR_TO_TB_CLASS_PROFESSOR_1" FOREIGN KEY (
	"PROFESSOR_NO"
)
REFERENCES "TB_PROFESSOR" (
	"PROFESSOR_NO"
);

ALTER TABLE "TB_PROFESSOR" ADD CONSTRAINT "FK_TB_DEPARTMENT_TO_TB_PROFESSOR_1" FOREIGN KEY (
	"DEPARTMENT_NO"
)
REFERENCES "TB_DEPARTMENT" (
	"DEPARTMENT_NO"
);

ALTER TABLE "TB_GRADE" ADD CONSTRAINT "FK_TB_STUDENT_TO_TB_GRADE_1" FOREIGN KEY (
	"STUDENT_NO"
)
REFERENCES "TB_STUDENT" (
	"STUDENT_NO"
);

ALTER TABLE "TB_GRADE" ADD CONSTRAINT "FK_TB_CLASS_TO_TB_GRADE_1" FOREIGN KEY (
	"CLASS_NO"
)
REFERENCES "TB_CLASS" (
	"CLASS_NO"
);